# Generated by Django 4.2.11 on 2024-06-09 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('nacimiento', models.DateField()),
                ('fecha_baja', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('dni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientes.cliente')),
                ('celular_emergencia', models.CharField(default=None, max_length=8, null=True)),
                ('altura', models.IntegerField(default=None, null=True)),
                ('peso', models.IntegerField(default=None, null=True)),
                ('obra_social', models.CharField(default=None, max_length=50, null=True)),
                ('consideraciones', models.TextField(default=None, null=True)),
            ],
        ),
    ]
