# Generated by Django 5.0.3 on 2024-03-06 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('dni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clientes.cliente')),
                ('celular_emergencia', models.CharField(default='Null', max_length=8)),
                ('altura', models.IntegerField(default=None, null=True)),
                ('peso', models.IntegerField(default=None, null=True)),
                ('obra_social', models.CharField(default='Null', max_length=50)),
                ('consideraciones', models.TextField(default='Null')),
            ],
        ),
    ]
