# Generated by Django 5.0.3 on 2024-03-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_fichamedica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_turno', models.CharField(max_length=15, verbose_name='día de la semana')),
                ('rango_turno', models.CharField(max_length=15, verbose_name='rango de horario de la clase')),
                ('cant_maxima', models.IntegerField(verbose_name='cupo máximo de alumnos por turno')),
            ],
        ),
    ]
