# Generated by Django 5.0.3 on 2024-03-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='id',
        ),
        migrations.AddField(
            model_name='turno',
            name='id_turno',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
