# Generated by Django 5.0.3 on 2024-03-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_paquete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
    ]
