# Generated by Django 5.0.3 on 2024-03-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_delete_paquete_delete_turno_delete_turnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='celular_emergencia',
            field=models.CharField(default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='consideraciones',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='obra_social',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
