# Generated by Django 5.0.3 on 2024-03-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_fichamedica_celular_emergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='celular_emergencia',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='consideraciones',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='obra_social',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
