# Generated by Django 5.0.3 on 2024-03-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_fichamedica_celular_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_baja',
            field=models.DateField(default=None, null=True),
        ),
    ]
