# Generated by Django 4.2.11 on 2024-06-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id_paquete', models.AutoField(primary_key=True, serialize=False)),
                ('cant_clas_sem', models.IntegerField()),
                ('precio_paquete', models.IntegerField()),
                ('fechaCaducidad_paquete', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
