# Generated by Django 5.0.2 on 2024-03-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_baja',
            field=models.DateField(default=None, null=True),
        ),
    ]
