# Generated by Django 5.0.2 on 2024-03-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0002_turno_fecha_baja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('dia_turno', models.CharField(max_length=15, verbose_name='día de la semana')),
                ('rango_turno', models.CharField(max_length=15, verbose_name='rango de horario de la clase')),
                ('cant_maxima', models.IntegerField(verbose_name='cupo máximo de alumnos por turno')),
                ('fecha_baja', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
