# Generated by Django 4.2.11 on 2024-06-09 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('Turnos', '__first__'),
        ('Paquetes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recibo', models.DateField()),
                ('importe', models.IntegerField()),
                ('métodoDePago', models.CharField(max_length=50)),
                ('usado', models.DateField(default=None, null=True)),
                ('dni', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'recibos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('DNI', models.CharField(max_length=10)),
                ('fecha_reserva', models.DateField()),
                ('id_paquete', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paquetes.paquete')),
                ('id_recibo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clases.recibo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_clase', models.DateField()),
                ('asistencia', models.BooleanField(default=None, null=True)),
                ('observaciones', models.TextField(default=None, null=True)),
                ('preparacion', models.TextField(default=None, null=True)),
                ('fecha_cancelado', models.DateField(default=None, null=True)),
                ('Force', models.BooleanField(default=False)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clases.reserva')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnos.turnos')),
                ('nueva_clase', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clases.clase')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
            },
        ),
    ]
