# Generated by Django 5.0.3 on 2024-03-13 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paquetes', '0001_initial'),
        ('Turnos', '0003_turnos_delete_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('DNI', models.CharField(max_length=10)),
                ('fecha_recibo', models.DateField()),
                ('importe', models.IntegerField()),
                ('métodoDePago', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'recibos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('DNI', models.CharField(max_length=10)),
                ('fecha_reserva', models.DateField()),
                ('id_paquete', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paquetes.paquete')),
                ('id_recibo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clases.recibo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_clase', models.DateField()),
                ('asistencia', models.BooleanField(default=None, null=True)),
                ('observaciones', models.TextField(default=None, null=True)),
                ('preparacion', models.TextField(default=None, null=True)),
                ('fecha_cancelado', models.DateField(default=None, null=True)),
                ('Force', models.BooleanField(default=False)),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turnos.turnos')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clases.reserva')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
            },
        ),
    ]
