# Generated by Django 5.0.3 on 2024-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='usado',
            field=models.DateField(default=None, null=True),
        ),
    ]
