# Generated by Django 5.0.3 on 2024-03-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clases', '0002_recibo_usado'),
        ('clientes', '0010_cliente_fecha_baja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='DNI',
        ),
        migrations.AddField(
            model_name='recibo',
            name='dni',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
