# Generated by Django 5.0.3 on 2024-03-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clases', '0003_remove_recibo_dni_recibo_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='nueva_clase',
            field=models.TextField(default=None, null=True),
        ),
    ]
